features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: true
  path: 'public://logo-white.png'
favicon:
  use_default: true
