palette:
  top: '#8e0605'
  bottom: '#c3221d'
  bg: '#ffffff'
  sidebar: '#f6f6f2'
  sidebarborders: '#f9f9f9'
  footer: '#292929'
  titleslogan: '#fffeff'
  text: '#3b3b3b'
  link: '#b3000a'
logo: 'public://color/bartik-80656513/logo.svg'
stylesheets:
  - 'public://color/bartik-80656513/colors.css'
files:
  - 'public://color/bartik-80656513/logo.svg'
  - 'public://color/bartik-80656513/colors.css'
