definitions:
  contact__site_page:
    enabled: false
    menu_name: footer
    parent: ''
    expanded: false
    weight: -50
  user__page:
    weight: -50
    menu_name: account
    parent: ''
    enabled: false
    expanded: false
  user__logout:
    weight: -45
    enabled: false
    menu_name: account
    parent: ''
    expanded: false
  standard__front_page:
    weight: -49
    menu_name: main
    parent: ''
    expanded: false
    enabled: true
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
